// OptiBike - Bike Fitting App
// Project-level build.gradle.kts
// Generated by Vibe Code (AI Agent)

plugins {
    id("com.android.application") version "8.3.0" apply false
    id("org.jetbrains.kotlin.android") version "1.9.20" apply false
    id("com.google.dagger.hilt.android") version "2.48" apply false
    id("androidx.room") version "2.6.1" apply false
}
