// OptiBike - Bike Fitting App
// settings.gradle.kts
// Generated by Vibe Code (AI Agent)

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "OptiBike"
include(":app")
