# OptiBike - ProGuard Rules
# proguard-rules.pro
# Generated by Vibe Code (AI Agent)

# Android default rules
-keep class androidx.** { *; }
-keep interface androidx.** { *; }

# Kotlin specific rules
-keep class kotlin.Metadata { *; }
-keep class kotlin.** { *; }
-keep interface kotlin.** { *; }

# Hilt (Dagger) rules
-keep class com.google.dagger.** { *; }
-keep interface com.google.dagger.** { *; }
-keep class dagger.** { *; }
-keep interface dagger.** { *; }
-keep class *_MembersInjector { *; }
-keep class *_Factory { *; }
-keep class *_ProvidesAdapter { *; }

# Room Database rules
-keep class androidx.room.** { *; }
-keep interface androidx.room.** { *; }
-keep class *_Impl { *; }
-keep class *_Database { *; }

# Coroutines rules
-keep class kotlinx.coroutines.** { *; }
-keep interface kotlinx.coroutines.** { *; }

# Compose rules
-keep class androidx.compose.** { *; }
-keep interface androidx.compose.** { *; }

# ARCore rules
-keep class com.google.ar.** { *; }
-keep interface com.google.ar.** { *; }

# iTextPDF rules
-keep class com.itextpdf.** { *; }
-keep interface com.itextpdf.** { *; }

# CameraX rules
-keep class androidx.camera.** { *; }
-keep interface androidx.camera.** { *; }

# Keep all Activities, Services, and BroadcastReceivers
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver

# Keep all ViewModels
-keep public class * extends androidx.lifecycle.ViewModel

# Keep all data classes (for Room, JSON serialization)
-keepclassmembers class * {
    public <init>(...);
}

# Keep all enum classes
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# Keep R (Resources) classes
-keep class **.R { *; }
-keep class **.R$* { *; }

# Keep all Parcelable classes
-keep class * implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator *;
}

# Keep all Serializable classes
-keepclassmembers class * implements java.io.Serializable {
    private <fields>;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
}

# Optimizations
-dontwarn okio.**
-dontwarn retrofit2.**
-dontwarn com.squareup.okhttp3.**
-dontwarn javax.annotation.**
-dontwarn org.jetbrains.annotations.**
